clusters:
- clusterName: demo1
  env: dev
  path: dev
- clusterName: demo1
  env: stage
  path: stage
- clusterName: demo1
  env: stage-a
  path: stage
- clusterName: demo1
  env: stage-b
  path: stage
- clusterName: demo1
  env: stage-c
  path: stage
- clusterName: demo1
  env: stage-d
  path: stage
- clusterName: demo1
  env: stage-e
  path: stage