apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-webhook-sensor
spec:
  dependencies:
    - name: github-webhook
      eventSourceName: github-webhook-source
      eventName: github
      filters:
        exprs:
        # Check the webhook action for for an opened or labeled issue
        - expr: action == "opened" || action == "labeled"
          fields:
          - name: action
            path: action
        data:
        - path: 'action,issue.labels.#(name="upgrade").name,issue.labels.#.name,issue.labels.#.name,issue.labels.#(name=="approved").name,label.name'
          type: string
          value:
            - '"opened","upgrade","cluster/.*","account/.*","approved"'
            - '"labeled","upgrade","cluster/.*","account/.*","approved",approved'

  triggers:
    - template:
        conditions: "github-webhook"
        name: upgrade-cluster-trigger
        log: {} # debug