apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-webhook-sensor
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github-cluster-upgrade-issue
      eventSourceName: github-webhook-source
      eventName: github
      filters:
        data:
        - path: 'body.action'
          type: string
          value:
            - "labeled"
        - path: 'body.label.name'
          type: string
          value:
            - "approved"
        - path: 'body.issue.state'
          type: string
          value:
            - "open"
        - path: 'body.issue.labels.#(name=="approved").name'
          type: string
          value:
            - "approved"
        - path: 'body.issue.labels.#(name=="upgrade").name'
          type: string
          value:
            - "upgrade"
        - path: 'body.issue.labels.#(name%"cluster*").name'
          type: string
          value:
            - "cluster/.*"
        - path: 'body.issue.labels.#(name%"account*").name'
          type: string
          value:
            - "account/.*"
  triggers:
    - template:
        name: upgrade-cluster-trigger
        argoWorkflow:
          operation: submit
          parameters:
          - src:
              dependencyName: github-cluster-upgrade-issue
              dataTemplate: 'cluster-upgrader-{{ .Input.body.issue.id }}'
            dest: metadata.name
          - src:
              dependencyName: github-cluster-upgrade-issue
              dataKey: body.issue.labels.#(name%"account*").name
            dest: spec.arguments.parameters.0.value
          source:
            resource:

              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: PLACEHOLDER
                namespace: cluster-upgrader
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: message
                      value: PLACEHOLDER
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: message
                    container:
                      image: docker/whalesay:latest
                      command: [cowsay]
                      args: ["{{inputs.parameters.message}}"]