apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-webhook-sensor
spec:
  dependencies:
    - name: github-webhook
      eventSourceName: github-webhook-source
      eventName: github
      filters:
        data:
        - path: 'body.action,body.issue.labels.#(name="upgrade").name,body.issue.labels.#.name,body.issue.labels.#.name,body.issue.labels.#(name=="approved").name,body.label.name'
          type: string
          value:
            - '"opened","upgrade","cluster/.*","account/.*","approved"'
            - '"labeled","upgrade","cluster/.*","account/.*","approved",approved'

  triggers:
    - template:
        conditions: "github-webhook"
        name: upgrade-cluster-trigger
        log: {} # debug