apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-webhook-sensor
spec:
  dependencies:
    - name: github-webhook
      eventSourceName: github-webhook-source
      eventName: github
      filters:
        data:
        - path: 'body.action'
          type: string
          value:
            - "labeled"
        - path: 'body.label.name'
          type: string
          value:
            - "approved"
        - path: 'body.issue.labels.#(name="approved").name'
          type: string
          value:
            - "approved"
        - path: 'body.issue.labels.#(name="upgrade").name'
          type: string
          value:
            - "upgrade"
        - path: 'body.issue.labels.#()#.name'
          type: string
          value:
            - ".*cluster/.*"
        - path: 'body.issue.labels.#()#.name'
          type: string
          value:
            - ".*account/.*"

  triggers:
    - template:
        conditions: "github-webhook"
        name: upgrade-cluster-trigger
        log: {} # debug