apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-webhook-sensor
spec:
  dependencies:
    - name: github-webhook
      eventSourceName: github-webhook-source
      eventName: github
      filters:
        data:
        - path: 'body.action,body.label.name,body.issue.labels.#(name="upgrade").name,body.issue.labels.#(name="approved").name,body.issue.labels.#()#.name,body.issue.labels.#()#.name'
          type: string
          value:
            - '"labeled","approved","upgrade","approved","cluster.*","account.*"'
        - path: 'body.issue.labels.#()#.name'
          type: string
          value:
            - ".*cluster/.*","account.*"
        - path: 'body.issue.labels.#()#.name'
          type: string
          value:
            - ".*account/.*"

  triggers:
    - template:
        conditions: "github-webhook"
        name: upgrade-cluster-trigger
        log: {} # debug