apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-webhook-sensor
spec:
  dependencies:
    - name: github-webhook
      eventSourceName: github-webhook-source
      eventName: github
      filters:
        data:
        - path: 'action,issue.labels.#.name,issue.labels.#.name,issue.labels.#.name,issue.labels.#.name,label.name'
          type: string
          value:
            - '"opened","upgrade","cluster/.*","account/.*","approved"'
            - '"labeled","upgrade","cluster/.*","account/.*","approved","approved"'

  triggers:
    - template:
        conditions: "github-webhook"
        name: upgrade-cluster-trigger
        log: {} # debug