apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-webhook-sensor
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: github-cluster-upgrade-issue
      eventSourceName: github-webhook-source
      eventName: github
      filters:
        data:
        - path: 'body.action'
          type: string
          value:
            - "labeled"
        - path: 'body.label.name'
          type: string
          value:
            - "approved"
        - path: 'body.issue.state'
          type: string
          value:
            - "open"
        - path: 'body.issue.labels.#(name=="approved").name'
          type: string
          value:
            - "approved"
        - path: 'body.issue.labels.#(name=="upgrade").name'
          type: string
          value:
            - "upgrade"
        - path: 'body.issue.labels.#(name%"cluster*").name'
          type: string
          value:
            - "cluster/.*"
        - path: 'body.issue.labels.#(name%"project*").name'
          type: string
          value:
            - "project/.*"
  triggers:
    - template:
        name: upgrade-cluster-trigger
        argoWorkflow:
          operation: submit
          parameters:
          - src:
              dependencyName: github-cluster-upgrade-issue
              contextTemplate: 'cluster-upgrader-{{ .Input.id | trunc 8}}'
            dest: metadata.name
          # - src:
          #     dependencyName: github-cluster-upgrade-issue
          #     dataKey: body.issue.labels.#(name%"project*").name
          #   dest: spec.arguments.parameters.0.value

          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                name: PLACEHOLDER
                namespace: cluster-upgrader
              spec:
                entrypoint: main
                templates:
                - name: main
                  dag:
                    tasks:
                    - name: pre-checks
                      template: pre-checks
                    - name: pre-checks-failed
                      depends: "pre-checks.Failed"
                      template: add-comment
                      arguments:
                        parameters:
                        - name: repo-owner
                          value: REPLACE_ME
                        - name: repo
                          value: REPLACE_ME
                        - name: issue
                          value: REPLACE_ME
                        - name: comment
                          value: REPLACE ME PRECHECKS FAILED
                    - name: pre-checks-succeeded
                      depends: "pre-checks.Succeeded"
                      template: add-comment
                      arguments:
                        parameters:
                        - name: repo-owner
                          value: REPLACE_ME
                        - name: repo
                          value: REPLACE_ME
                        - name: issue
                          value: REPLACE_ME
                        - name: comment
                          value: REPLACE ME PRECHECKS SUCCEEDED
                    - name: upgrade-cluster
                      depends: "pre-checks-succeeded.Succeeded"
                      template: upgrade-cluster
                      arguments:
                        parameters:
                        - name: version
                          value: REPLACE_ME
                        - name: cluster
                          value: REPLACE_ME
                        - name: project
                          value: REPLACE_ME
                    - name: validate-upgrade
                      depends: "upgrade-cluster.Succeeded"
                      template: validate-upgrade
                      arguments:
                        parameters:
                        - name: version
                          value: REPLACE_ME
                        - name: cluster
                          value: REPLACE_ME
                        - name: project
                          value: REPLACE_ME
                    - name: validate-upgrade-failed
                      depends: "validate-upgrade.Failed"
                      template: add-comment
                      arguments:
                        parameters:
                        - name: repo-owner
                          value: REPLACE_ME
                        - name: repo
                          value: REPLACE_ME
                        - name: issue
                          value: REPLACE_ME
                        - name: comment
                          value: REPLACE ME VALIDATE UPGRADE FAILED
                    - name: validate-upgrade-succeeded
                      depends: "validate-upgrade.Succeeded"
                      template: add-comment
                      arguments:
                        parameters:
                        - name: repo-owner
                          value: REPLACE_ME
                        - name: repo
                          value: REPLACE_ME
                        - name: issue
                          value: REPLACE_ME
                        - name: comment
                          value: "REPLACE ME VALIDATE UPGRADE FAILED"
                    - name: close-issue
                      depends: "validate-upgrade-succeeded.Succeeded"
                      template: close-issue
                      arguments:
                        parameters:
                        - name: repo-owner
                          value: REPLACE_ME
                        - name: repo
                          value: REPLACE_ME
                        - name: issue
                          value: REPLACE_ME

                - name: add-comment
                  inputs:
                    parameters:
                    - name: repo-owner
                    - name: repo
                    - name: issue
                    - name: comment
                  http:
                    url: "https://api.github.com/repos/{{inputs.parameters.repo-owner}}/{{inputs.parameters.repo}}/issues/{{inputs.parameters.issue}}/comments"
                    method: "POST"
                    headers:
                    - name: Content-Type
                      value: application/json
                    - name: Authorization
                      valueFrom:
                        secretKeyRef:
                          key: DEMO_GH_PAT
                          name: cluster-upgrade-secret
                    successCondition: "response.statusCode == 200"
                    body: '{"body":"{{inputs.parameters.comment}}"}'

                - name: pre-checks
                  container:
                    image: docker/whalesay
                    command: [cowsay]
                    args: ["Moo"]

                - name: upgrade-cluster
                  inputs:
                    parameters:
                    - name: version
                    - name: cluster
                    - name: project
                  container:
                    image: docker/whalesay
                    command: [cowsay]
                    args: ["Moo"]

                - name: validate-upgrade
                  inputs:
                    parameters:
                    - name: version
                    - name: cluster
                    - name: project
                  container:
                    image: docker/whalesay
                    command: [cowsay]
                    args: ["Moo"]

                - name: close-issue
                  inputs:
                    parameters:
                    - name: repo-owner
                    - name: repo
                    - name: issue
                  container:
                    image: docker/whalesay
                    command: [cowsay]
                    args: ["Moo"]