apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-webhook-source
spec:
  service:
    ports:
      - port: 30100
        targetPort: 30100
  webhook:
    github:
      port: "30100"
      endpoint: /github
      method: POST
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-eventsource
spec:
  ports:
  - port: 30100
    protocol: TCP
    targetPort: 30100
    nodePort: 30100
  selector:
    eventsource-name: github-webhook-source
  type: NodePort