apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-webhook-source
spec:
  service:
    ports:
      - port: 30100
        targetPort: 30100
  webhook:
    github:
      port: "30100"
      endpoint: /github
      method: POST