apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: cluster-upgrade
  annotations:
     argocd.argoproj.io/hook: PreSync
spec:
  entrypoint: main
  serviceAccountName: default
  ttlStrategy:
    secondsAfterCompletion: 300
  templates:
  - name: main
    steps:
      - - name: pre-validation
          template: pre-validation

      # pre-validation succeeds
      - - name: create-github-issue
          template: create-github-issue
          dependencies: ["pre-validation"]
      - - name: k8s-control-plane-upgrade
          template: k8s-control-plane-upgrade
      - - name: k8s-node-upgrade
          template: k8s-node-upgrade
      - - name: post-validation
          template: post-validation
      - - name: update-github-issue
          template: update-github-issue

  - name: create-color-external-secret
    resource:
      action: create
      setOwnerReference: true
      successCondition: status.conditions.0.status == True
      failureCondition: status.conditions.0.status == False
      manifest: |
        apiVersion: external-secrets.io/v1beta1
        kind: ExternalSecret
        metadata:
          name: color-test
        spec:
          refreshInterval: '0'
          secretStoreRef:
            kind: ClusterSecretStore
            name: gcp
          target:
            name: color-test
            creationPolicy: Owner
          data:
          - secretKey: COLOR
            remoteRef:
              key: COLOR
  - name: get-color-secret
    outputs:
      parameters:
      - name: color
        valueFrom:
          jsonPath: '{.data.COLOR}'
    resource:
      action: get
      manifest: |
        apiVersion: v1
        kind: Secret
        metadata:
          name: color-test
  - name: evaluate-color
    inputs:
      parameters:
      - name: color
    container:
      image: ubuntu:20.04
      command:
      - /bin/bash
      - -c
      - |
        set -x
        export COLOR=$(echo "{{inputs.parameters.color}}" | base64 -d -)
        case ${COLOR} in
          red)
            exit 0
            ;;
          yellow)
            exit 0
            ;;
          blue)
            exit 0
            ;;
          green)
            exit 0
            ;;
          purple)
            exit 0
            ;;
          orange)
            exit 0
            ;;
          *)
            echo "${COLOR} is invalid!"
            exit 1
            ;;
        esac
  - name: touch-external-secret
    resource:
      action: patch
      mergeStrategy: json
      flags:
      - externalsecrets.external-secrets.io
      - postsync-validation-deploy-cm
      manifest: |
        - op: replace
          path: /metadata/annotations/akuity.io~1refreshedAt
          value: "{{workflow.creationTimestamp}}"